PlayGrounds/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("slots/", include("slots.urls", namespace="slots")),
    path("bookings/", include("bookings.urls", namespace="bookings")),
    path("accounts/", include("users.urls", namespace="accounts")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# urlpatterns += [path("PlyHub", RedirectView.as_view(url="", permanent=True))]

bookings/urls.py
from django.urls import path
from . import views

app_name = "bookings"
urlpatterns = [
    path("", views.BookingList.as_view(), name="booking_list"),
    path("bookings/make-booking/<int:id>/", views.create_booking, name="make_booking"),
    path("bookings/accept/<int:id>/", views.accept_booking, name="booking_accept"),
    path("bookings/reject/<int:id>/", views.reject_booking, name="booking_reject"),
    path("bookings/cancel/<int:id>/", views.cancel_booking, name="booking_cancel"),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"
urlpatterns = [
    path("", views.home, name="home"),
    path("playgrounds/", views.PlaygroundsList.as_view(), name="playground_list"),
    path(
        "playgrounds/<int:pk>/<slug:name>/",
        views.PlaygroundDetail.as_view(),
        name="playground_detail",
    ),
    path(
        "playgrounds/create/",
        views.PlaygroundCreate.as_view(),
        name="playground_create",
    ),
    path(
        "playgrounds/update/<int:pk>/<slug:name>/",
        views.PlaygroundUpdate.as_view(),
        name="playground_update",
    ),
    path(
        "playgrounds/delete/<int:pk>/<slug:name>/",
        views.PlaygroundDelete.as_view(),
        name="playground_delete",
    ),
    path("playground-filter/", views.filter, name="playground_filter"),
]

slots/urls.py
from django.urls import path
from . import views

app_name = "slots"
urlpatterns = [
    path("", views.SlotList.as_view(), name="slot_list"),
    path("slots/create/", views.SlotCreate.as_view(), name="slot_create"),
    path("slots/update/<int:pk>/", views.SlotUpdate.as_view(), name="slot_update"),
    path("slots/delete/<int:pk>/", views.SlotDelete.as_view(), name="slot_delete"),
]

slots/models.py
from django.db import models
from django.db.models.query import QuerySet
from core.models import Playground
from django.core.validators import MinValueValidator
import datetime
from django.db.models import Q


class FreeManager(models.Manager):
    def get_queryset(self) -> QuerySet:
        return (
            super()
            .get_queryset()
            .filter(Q(status="free") & Q(day__gte=datetime.date.today()))
        )


class BookedManager(models.Manager):
    def get_queryset(self) -> QuerySet:
        return super().get_queryset().filter(status="booked")


class Slot(models.Model):
    class Status(models.TextChoices):
        FREE = "free", "free"
        BOOKED = "booked", "booked"

    day = models.DateField()
    start_hour = models.TimeField()
    end_hour = models.TimeField()

    price = models.IntegerField(validators=[MinValueValidator(1)])
    playground = models.ForeignKey(
        Playground, on_delete=models.CASCADE, related_name="slots"
    )

    status = models.CharField(
        max_length=10,
        choices=Status.choices,
        default=Status.FREE,
        blank=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    free_slots = FreeManager()
    booked_slots = BookedManager()

    class Meta:
        ordering = ["-created_at"]
        unique_together = [("day", "start_hour", "end_hour", "playground")]
        verbose_name = "Slot"
        verbose_name_plural = "Slots"

    def save(self, *args, **kwargs):
        if not self.status:
            self.status = self.Status.FREE
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f"{self.playground}-{self.day}-{self.start_hour}:{self.end_hour} Price:{self.price}"

slots/forms.py
from django import forms
from .models import Slot
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _
from django.db.models import Q
import datetime


class SlotForm(forms.ModelForm):
    day = forms.DateField(
        widget=forms.DateInput(
            attrs={
                "class": "form-control",
                "type": "date",
                "min": datetime.date.today(),
                "max": datetime.date.today() + datetime.timedelta(weeks=1),
            }
        )
    )
    start_hour = forms.TimeField(
        widget=forms.TimeInput(
            attrs={
                "class": "form-control",
                "type": "time",
            }
        )
    )

    end_hour = forms.TimeField(
        widget=forms.TimeInput(
            attrs={
                "class": "form-control",
                "type": "time",
            }
        )
    )
    price = forms.IntegerField(
        label="",
        widget=forms.NumberInput(
            attrs={
                "placeholder": "Price",
                "class": "form-control",
                "type": "number",
                "autocomplete": "off",
            },
        ),
    )

    class Meta:
        model = Slot
        fields = ["day", "start_hour", "end_hour", "price", "playground"]

        widgets = {
            "playground": forms.Select(
                attrs={
                    "class": "form-select",
                }
            )
        }

    def clean_day(self):
        day = self.cleaned_data["day"]
        if day is None or (
            day < datetime.date.today()
            or day > datetime.date.today() + datetime.timedelta(weeks=1)
        ):
            raise ValidationError("invalid day")

        return day

    def clean_end_hour(self):
        start_hour = self.cleaned_data.get("start_hour")
        end_hour = self.cleaned_data.get("end_hour")
        if end_hour < start_hour:
            raise forms.ValidationError(_("End hour must be greater than start hour"))

        if (
            start_hour.minute != 0
            or start_hour.second != 0
            or end_hour.minute != 0
            or end_hour.second != 0
        ):
            raise forms.ValidationError(
                _("Slots must have full-hour start and end times")
            )
        return end_hour

    def clean_price(self):
        price = self.cleaned_data["price"]

        if price is None or price < 0:
            raise ValidationError("Slot price must be greater than 0")
        return price

    def save(self, commit=True):
        slot = super().save(commit=False)

        day = slot.day
        start_hour = slot.start_hour
        end_hour = slot.end_hour
        playground = slot.playground

        if Slot.objects.exclude(id=self.instance.id).filter(
            Q(playground=playground)
            & Q(day=day)
            & Q(start_hour=start_hour)
            & Q(end_hour=end_hour)
        ):
            raise forms.ValidationError(
                "Slots with this information already exist",
            )

        if commit:
            slot.save()
        return slot

slots/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from .models import Slot
from django.contrib import messages
from django.urls import reverse_lazy
from .forms import SlotForm
from django.contrib.auth.mixins import LoginRequiredMixin
from core.mixins import CreateMixin, OwnerRequiredMixin


class SlotList(LoginRequiredMixin, ListView):
    model = Slot
    context_object_name = "slots"
    paginate_by = 10

    def get_queryset(self):
        qs = Slot.free_slots.all()
        if self.request.user.role == "Player":
            return qs

        return qs.filter(playground__in=self.request.user.playgrounds.all())


class SlotCreate(LoginRequiredMixin, CreateMixin, CreateView):
    model = Slot
    success_url = reverse_lazy("slots:slot_list")
    form_class = SlotForm

    # limit playground to only those owned by owner
    def get_form_class(self):
        modelform = super().get_form_class()
        modelform.base_fields["playground"].limit_choices_to = {
            "owner": self.request.user
        }
        return modelform

    def form_valid(self, form):
        messages.success(self.request, "Slot is added successfully")
        return super(SlotCreate, self).form_valid(form)


class SlotUpdate(LoginRequiredMixin, UpdateView):
    model = Slot
    success_url = reverse_lazy("slots:slot_list")
    context_object_name = "slot"
    form_class = SlotForm

    def form_valid(self, form):
        messages.success(self.request, "Slot is updated successfully")
        return super(SlotUpdate, self).form_valid(form)


class SlotDelete(LoginRequiredMixin, OwnerRequiredMixin, DeleteView):
    model = Slot
    success_url = reverse_lazy("slots:slot_list")

    def form_valid(self, form):
        messages.success(self.request, "Slot is deleted successfully")
        return super(SlotDelete, self).form_valid(form)

slots/templates/slots/slot_confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="center">
    <form action="" method="post">
        {% csrf_token %}
        <h2>Delete Slot</h2>
        <p>Are you sure that want to delete this slot</p>
        <p class="form-buttons">
            <input type="submit" value="Delete" class="btn btn-outline-danger">
            <a href="{%url 'slots:slot_list'%}" class="btn btn-outline-secondary">Cancel</a>
        </p>
    </form>
</div>
{% endblock content %}

slots/templates/slots/slot_form.html
{% extends "base.html" %}

{% block content %}
<div class="center">
    <form action="" method="post" class="custome-card" novalidate>
        {% csrf_token %}
        <h2 class="text-center"> {% if slot %}
            Update
            {%else%}
            Add
            {% endif %} Slot</h2>
        {% if form.errors %}
            <small class="error">{{form.errors|striptags}}</small>
        {% endif %}
        {% for field in form%}
        {{field.label_tag}}
        {{field}}
        {% if field.errors %}
        <small class="error">{{field.errors|striptags}}</small>
        {% endif %}
        {% endfor %}
        <input type="submit" value="{%if slot%}Update{%else%}Add{% endif %}" class="btn btn-outline-primary full-width">
    </form>
</div>
{% endblock content %}

slots/templates/slots/slot_list.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    {% if user.role == 'Owner' %}
    <div class="d-flex align-items-center justify-content-center mb-4">
        <a href="{% url 'slots:slot_create' %}" class="btn btn-outline-dark">Add Slot</a>
    </div>
    {% endif %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Playground</th>
                <th scope="col">Day</th>
                <th scope="col">Start</th>
                <th scope="col">End</th>
                <th scope="col">Price</th>
                <th scope="col"></th>

            </tr>
        </thead>
        <tbody>
            {% for slot in slots%}
            <tr>
                <td><a href="{{slot.playground.get_absolute_url}}">{{slot.playground.name}}</a></td>
                <td>{{slot.day}}</td>
                <td>{{slot.start_hour}}</td>
                <td>{{slot.end_hour}}</td>
                <td>{{slot.price}}$</td>
                <td>
                    {% if user.role == 'Player' %}
                    <a href="{% url 'bookings:make_booking' slot.id%}" class="btn btn-outline-primary">Book</a>
                    {% endif %}
                    {% if user.role == 'Owner' %}
                    <a href="{% url 'slots:slot_update' slot.id%}" class="btn btn-outline-primary">Update</a>
                    <a href="{% url 'slots:slot_delete' slot.id%}" class="btn btn-outline-danger">Delete</a>
                    {% endif %}
                </td>

            </tr>
            {% endfor %}

        </tbody>
    </table>
</div>
<hr>
{% endblock content %}