PlayGrounds/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("slots/", include("slots.urls", namespace="slots")),
    path("bookings/", include("bookings.urls", namespace="bookings")),
    path("accounts/", include("users.urls", namespace="accounts")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# urlpatterns += [path("PlyHub", RedirectView.as_view(url="", permanent=True))]

bookings/urls.py
from django.urls import path
from . import views

app_name = "bookings"
urlpatterns = [
    path("", views.BookingList.as_view(), name="booking_list"),
    path("bookings/make-booking/<int:id>/", views.create_booking, name="make_booking"),
    path("bookings/accept/<int:id>/", views.accept_booking, name="booking_accept"),
    path("bookings/reject/<int:id>/", views.reject_booking, name="booking_reject"),
    path("bookings/cancel/<int:id>/", views.cancel_booking, name="booking_cancel"),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"
urlpatterns = [
    path("", views.home, name="home"),
    path("playgrounds/", views.PlaygroundsList.as_view(), name="playground_list"),
    path(
        "playgrounds/<int:pk>/<slug:name>/",
        views.PlaygroundDetail.as_view(),
        name="playground_detail",
    ),
    path(
        "playgrounds/create/",
        views.PlaygroundCreate.as_view(),
        name="playground_create",
    ),
    path(
        "playgrounds/update/<int:pk>/<slug:name>/",
        views.PlaygroundUpdate.as_view(),
        name="playground_update",
    ),
    path(
        "playgrounds/delete/<int:pk>/<slug:name>/",
        views.PlaygroundDelete.as_view(),
        name="playground_delete",
    ),
    path("playground-filter/", views.filter, name="playground_filter"),
]

bookings/models.py
from django.db import models
from django.db.models.query import QuerySet
from slots.models import Slot
from django.contrib.auth import get_user_model

User = get_user_model()


class PendingManager(models.Manager):
    def get_queryset(self) -> QuerySet:
        return super().get_queryset().filter(status="pending")


class Booking(models.Model):
    class Status(models.TextChoices):
        ACCEPTED = "accepted", "accepted"
        REJECTED = "rejected", "rejected"
        PENDING = "pending", "pending"

    slot = models.OneToOneField(Slot, on_delete=models.CASCADE)
    player = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bookings")
    status = models.CharField(
        max_length=10, choices=Status.choices, default=Status.PENDING
    )
    objects = models.Manager()
    pending = PendingManager() 
    class Meta:
        unique_together = [("slot", "player")]
        verbose_name = "Booking"
        verbose_name_plural = "Bookings"

    def __str__(self):
        return f"{self.player} booked {self.slot}"

bookings/views.py
from django.contrib import messages
from django.views.generic.list import ListView
from .models import Booking
from django.contrib.auth.mixins import LoginRequiredMixin
from core.models import Playground
from slots.models import Slot
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.exceptions import PermissionDenied

# Create your views here.


class BookingList(LoginRequiredMixin, ListView):
    model = Booking
    context_object_name = "bookings"
    paginate_by = 10

    def get_queryset(self):
        if self.request.user.role == "Owner":
            playgrounds = Playground.objects.filter(owner=self.request.user)
            playgrounds_slots = Slot.objects.filter(playground__in=playgrounds)
            return Booking.objects.filter(slot__in=playgrounds_slots)
        return Booking.objects.filter(player=self.request.user).order_by("slot")


@login_required()
def create_booking(request, id):
    if request.user.role == "Owner":
        raise PermissionDenied()

    slot_to_book = Slot.objects.get(pk=id)
    booking_before = Booking.objects.filter(
        Q(player=request.user) & Q(slot=slot_to_book)
    )
    if booking_before:
        messages.info(request, "Your already make a request for this slot")
        return redirect("bookings:booking_list")

    booking = Booking.objects.create(player=request.user, slot=slot_to_book)
    booking.save()
    return redirect("bookings:booking_list")


@login_required()
def accept_booking(request, id):
    booking = get_object_or_404(Booking, pk=id)
    if booking.slot.playground.owner != request.user:
        raise PermissionDenied()
    slot = Slot.objects.get(pk=booking.slot.id)
    slot.status = "BOOKED"
    slot.save()
    booking.status = "accepted"
    booking.save()
    return redirect("bookings:booking_list")


@login_required()
def reject_booking(request, id):
    booking = get_object_or_404(Booking, pk=id)
    if booking.slot.playground.owner != request.user:
        raise PermissionDenied()
    booking.status = "rejected"
    booking.save()
    return redirect("bookings:booking_list")


@login_required()
def cancel_booking(request, id):
    booking = get_object_or_404(Booking, pk=id)
    if request.user != booking.player:
        raise PermissionDenied()
    booking.delete()
    messages.info(request, "booking is canceled")
    return redirect("bookings:booking_list")

bookings/templates/bookings/booking_list.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>Booking Requests</h1>
    <table class="table">
        <thead>
            <tr>
                {% if user.role == 'Owner' %}
                <th scope="col">Player</th>
                {% endif %}
                <th scope="col">Playground</th>
                <th scope="col">Day</th>
                <th scope="col">Start</th>
                <th scope="col">End</th>
                <th scope="col">Price</th>
                <th scope="col">Status</th>
                <th scope="col"></th>


            </tr>
        </thead>
        <tbody>
            {% for booking in bookings%}
            <tr>
                {% if user.role == 'Owner' %}
                <td>{{booking.player}}</td>
                {% endif %}
                <td>{{booking.slot.playground.name}}</td>
                <td>{{booking.slot.day}}</td>
                <td>{{booking.slot.start_hour}}</td>
                <td>{{booking.slot.end_hour}}</td>
                <td>{{booking.slot.price}}$</td>

                {% if user.role == 'Player'%}
                <td>
                    <p class='alert alert-{% if booking.status == "pending" %}warning{% elif booking.status == "accepted" %}success
{% else %}error{% endif %}'>
                        {{booking.status|title}}
                    </p>
                </td>
                {% if booking.status == "pending"%}
                <td>
                    <a href="{%url 'bookings:booking_cancel' booking.id%}" class="btn btn-outline-secondary">Cancel</a>

                </td>
                {% endif %}
                {% else%}
                <td>
                    {% if booking.status == "pending"%}
                    <a href="{% url 'bookings:booking_accept' booking.id%}" class="btn btn-outline-success">Accept</a>
                    <a href="{% url 'bookings:booking_reject' booking.id%}" class="btn btn-outline-danger">Reject</a>
                    {%else%}
                    <p class='alert alert-{% if booking.status == "pending" %}warning{% elif booking.status == "accepted" %}success
{% else %}error{% endif %}'>
                        {{booking.status|title}}
                    </p>
                    {% endif %}
                </td>
                {% endif %}


            </tr>
            {% endfor %}

        </tbody>
    </table>
</div>
<hr>
{% endblock content %}