PlayGrounds/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("slots/", include("slots.urls", namespace="slots")),
    path("bookings/", include("bookings.urls", namespace="bookings")),
    path("accounts/", include("users.urls", namespace="accounts")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# urlpatterns += [path("PlyHub", RedirectView.as_view(url="", permanent=True))]

core/urls.py
from django.urls import path
from . import views

app_name = "core"
urlpatterns = [
    path("", views.home, name="home"),
    path("playgrounds/", views.PlaygroundsList.as_view(), name="playground_list"),
    path(
        "playgrounds/<int:pk>/<slug:name>/",
        views.PlaygroundDetail.as_view(),
        name="playground_detail",
    ),
    path(
        "playgrounds/create/",
        views.PlaygroundCreate.as_view(),
        name="playground_create",
    ),
    path(
        "playgrounds/update/<int:pk>/<slug:name>/",
        views.PlaygroundUpdate.as_view(),
        name="playground_update",
    ),
    path(
        "playgrounds/delete/<int:pk>/<slug:name>/",
        views.PlaygroundDelete.as_view(),
        name="playground_delete",
    ),
    path("playground-filter/", views.filter, name="playground_filter"),
]

core/models.py
from django.db import models
from django.contrib.auth import get_user_model
from .utils import cites_choices
from django.utils.text import slugify
from users.models import CustomUser
from django.urls import reverse
from PIL import Image
from django.core.exceptions import ValidationError

User = get_user_model()


def validate_image(image):
    try:
        image = Image.open(image)
    except (IOError, ValueError):
        raise ValidationError("Invalid Image format")

    max_size = 2 * 1024 * 1024
    if image.size > max_size:
        raise ValidationError("Image size must be less than 2MB")


class Attachment(models.Model):
    image = models.ImageField(
        blank=True,
        upload_to="attachments/",
        verbose_name="Images",
        validators=[validate_image],
        help_text="Allowed files are images with size less than or equal 2MB",
    )
    playground = models.ForeignKey(
        "Playground",
        related_name="images",
        on_delete=models.CASCADE,
    )


class Playground(models.Model):
    class Grass(models.TextChoices):
        ARTIFICIAL = "artificial", "artificial"
        NATURAL = "natural", "natural"

    CAPACITY_CHOICES = [(5, 5), (7, 7), (11, 11)]

    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=255, null=True, blank=True)
    capacity = models.IntegerField(choices=CAPACITY_CHOICES, default=5)
    # address = models.CharField(max_length=255)
    city = models.CharField(max_length=255, choices=cites_choices)
    grass_type = models.CharField(
        max_length=15, choices=Grass.choices, default=Grass.ARTIFICIAL
    )
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="playgrounds"
    )
    image = models.ImageField(upload_to="playgrounds_images/")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (("name", "city"),)
        ordering = ["name", "-created_at"]
        indexes = [
            models.Index(fields=["name"]),
            models.Index(fields=["city"]),
            models.Index(fields=["-created_at"]),
        ]

    def __str__(self) -> str:
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        if self.owner.role == CustomUser.Role.PLAYER:
            raise PermissionError("only owners can add playgrounds")
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "core:playground_detail", kwargs={"pk": self.pk, "name": self.slug}
        )

core/forms.py
from django import forms
from .models import Playground, Attachment
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from .models import Playground
from django.db.models import Q


class PlaygroundForm(forms.ModelForm):
    name = forms.CharField(
        help_text="name should consist of characters only",
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Playground Name",
                "class": "form-control",
                "autocomplete": "off",
            }
        ),
    )

    city = forms.Select()

    image = forms.ImageField(
        label="Choose an image for Playground",
        widget=forms.FileInput(
            attrs={
                "class": "form-control form-control-sm",
            }
        ),
    )
    capacity = forms.RadioSelect()
    grass_type = forms.RadioSelect()

    class Meta:
        model = Playground
        fields = [
            "name",
            "city",
            "capacity",
            "grass_type",
            "image",
        ]

    def clean(self):
        data = self.cleaned_data
        name = data.get("name")
        city = data.get("city")

        if Playground.objects.exclude(id=self.instance.id).filter(
            Q(name=name) & Q(city=city)
        ):
            raise forms.ValidationError(
                "Playground with this name and city already exist"
            )
        return data


# allow owners to add multiple images to playground
# class PlaygroundImageForm(PlaygroundForm):
#     file = forms.FileField(widget=forms.ClearableFileInput(attrs={"multiple": True}))

#     class Meta(PlaygroundForm.Meta):
#         fields = PlaygroundForm.Meta.fields + [
#             "file",
#         ]

core/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.urls import reverse_lazy
from .models import Playground, Attachment
from .forms import PlaygroundForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext as _
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.forms import ImageField
from .mixins import OwnerRequiredMixin, CreateMixin


# Create your views here.


def home(request):
    return render(request, "home.html")


class PlaygroundsList(LoginRequiredMixin, ListView):
    model = Playground
    context_object_name = "playgrounds"
    paginate_by = 10

    def get_queryset(self):
        name = self.request.GET.get("name", "")
        capacity = self.request.GET.get("capacity", "")
        ttype = self.request.GET.get("type", "")

        qs = Playground.objects.all()

        if name:
            name = name.strip()
            qs = qs.filter(Q(name__icontains=name) | Q(city__icontains=name))
        if capacity:
            qs = qs.filter(capacity=capacity)
        if ttype:
            qs = qs.filter(grass_type=ttype)

        if self.request.user.role == "Owner":
            return qs.filter(owner=self.request.user)
        return qs


class PlaygroundDetail(LoginRequiredMixin, DetailView):
    model = Playground
    context_object_name = "playground"


class PlaygroundCreate(LoginRequiredMixin, CreateMixin, CreateView):
    model = Playground
    form_class = PlaygroundForm
    success_url = reverse_lazy("core:playground_list")

    def form_valid(self, form):
        playground = form.save(commit=False)
        playground.owner = self.request.user
        playground.save()

        additional_images = self.request.FILES.getlist("additional_images")
        if additional_images:
            for img in additional_images:
                Attachment.objects.create(playground=playground, image=img)
        messages.success(self.request, f"Playground is created successfully")
        return super(PlaygroundCreate, self).form_valid(form)


class PlaygroundUpdate(LoginRequiredMixin, OwnerRequiredMixin, UpdateView):
    model = Playground
    form_class = PlaygroundForm

    def get_form_class(self):
        obj = self.get_object()
        model_form = super().get_form_class()
        model_form.base_fields["image"] = ImageField(initial=obj.image)
        return model_form

    success_url = reverse_lazy("core:playground_list")
    context_object_name = "playground"

    def form_valid(self, form):
        messages.info(self.request, "Playground info is updated successfully")
        additional_images = self.request.FILES.getlist("additional_images")
        if additional_images:
            for img in additional_images:
                Attachment.objects.create(playground=form.instance, image=img)
        return super(PlaygroundUpdate, self).form_valid(form)


class PlaygroundDelete(LoginRequiredMixin, OwnerRequiredMixin, DeleteView):
    model = Playground
    context_object_name = "playground"
    success_url = reverse_lazy("core:playground_list")
    raise_exception = True

    def form_valid(self, form):
        messages.info(self.request, "Playground is deleted successfully")
        return super(PlaygroundDelete, self).form_valid(form)


@login_required()
def filter(request):
    return render(request, "filter_form.html")

core/templates/core/playground_confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="center">
    <form action="" method="post">
        {% csrf_token %}
        <h2>Delete Playground</h2>
        <p>Are you sure that want to delete {{playground.name}} playground</p>
        <p class="form-buttons">
            <input type="submit" value="Delete" class="btn btn-outline-danger">
            <a href="{%url 'core:playground_list'%}" class="btn btn-outline-secondary">Cancel</a>
        </p>
    </form>
</div>
{% endblock content %}

core/templates/core/playground_detail.html
{% extends "base.html" %} 
{% block content %}
<div class="container">
  <div class="card my-4">
    <div class="card-body">
      <h5 class="card-title">{{ playground.name }}</h5>
      <div class="card-text">
        <div class="row">
          <div class="col-md-6">
            <p class="mb-1"><i class="fas fa-map-marker-alt mr-2"></i> City: {{ playground.city }}</p>
            <p class="mb-1"><i class="fas fa-user mr-2"></i> Owner: {{ playground.owner.fullname }}</p>
            <p class="mb-1"><i class="fas fa-users mr-2"></i> Capacity: {{ playground.capacity }}</p>
            <p class="mb-1"><i class="fas fa-seedling mr-2"></i> Grass Type: {{ playground.grass_type|title }}</p>
          </div>
          {% if user.role == 'Owner' and playground.owner == user %}
            <div class="col-md-6 text-md-right">
              <a href="{% url 'core:playground_update' playground.id playground.slug %}" class="btn btn-outline-primary mr-2">Update</a>
              <a href="{% url 'core:playground_delete' playground.id playground.slug %}" class="btn btn-outline-danger">Delete</a>
            </div>
          {% endif %}
        </div>
      </div>

      <div id="carouselExampleControls" class="carousel slide mt-4" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100 img-fluid" src="{{ playground.image.url }}" alt="First slide">
          </div>
          {% with attachments=playground.images.all %}
            {% if attachments %}
              {% for image in attachments %}
                <div class="carousel-item">
                  <img class="d-block w-100 img-fluid" src="{{ image.image.url }}" alt="Slide">
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

core/templates/core/playground_form.html
{% extends "base.html" %}

{% block content %}
<div class="center">
    <form action="" method="post" class="custome-card" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        <h2 class="text-center">{% if ground %}
            Update
            {%else%}
            Add
            {% endif %} Playground</h2>
        {% for field in form%}
        {{field.label_tag}}
        {{field}}
        {% if field.errors %}
        <small class="error">{{field.errors|striptags}}</small>
        {% endif %}
        {% endfor %}
        <label for="additional_images">Additional Playground Images:</label>
        <input type="file" name="additional_images" id="additional_images" multiple  accept="image/*">
        <input type="submit" value="{% if ground %}Update{%else%}Add{%endif%}"
            class="btn btn-outline-primary full-width">
    </form>
</div>
{% endblock content %}

core/templates/core/playground_list.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block content %}
<section class="py-5">
    <div class="container">
        <div class="mb-4 d-md-flex justify-content-between align-items-center">
            <div class="mb-3 mb-md-0">
                <a href="{% url 'core:playground_filter' %}" class="btn btn-outline-primary mr-2">Filter</a>
                <a href="{% url 'core:playground_list' %}" class="btn btn-outline-warning mr-2">Clear Filter</a>
                {% if user.role == 'Owner' %}
                <a href="{% url 'core:playground_create' %}" class="btn btn-dark">Add Playground</a>
                {% endif %}
            </div>
        </div>
        <div class="row">
            {% for playground in playgrounds %}
            <div class="col-md-6 col-lg-4 mb-4">
                <div class="card shadow-sm border-light h-100">
                    {% thumbnail playground.image 400x400 crop="smart" as im %}
                    <a href="{{ playground.get_absolute_url }}" class="position-relative d-block overflow-hidden">
                        <img src="{{ im.url }}" class="card-img-top" alt="{{ playground.name }}">
                    </a>
                    <div class="card-body">
                        <a href="{{ playground.get_absolute_url }}" class="text-decoration-none">
                            <h5 class="card-title mb-3">{{ playground.name }}</h5>
                        </a>
                        <div class="post-meta mb-3">
                            <i class="fas fa-map-marker-alt text-muted mr-2"></i>
                            {{ playground.city }}
                        </div>
                        <div class="post-meta mb-3">
                            <i class="fas fa-user text-muted mr-2"></i>
                            {{ playground.owner.fullname }}
                        </div>
                        <div class="d-flex justify-content-between">
                            <div>
                                <span class="text-muted font-small d-block mb-2">Type</span>
                                <span class="h6 text-dark font-weight-bold">{{ playground.grass_type|title }}</span>
                            </div>
                            <div>
                                <span class="text-muted font-small d-block mb-2">Capacity</span>
                                <span class="h6 text-dark font-weight-bold">{{ playground.capacity }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock content %}