PlayGrounds/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("slots/", include("slots.urls", namespace="slots")),
    path("bookings/", include("bookings.urls", namespace="bookings")),
    path("accounts/", include("users.urls", namespace="accounts")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# urlpatterns += [path("PlyHub", RedirectView.as_view(url="", permanent=True))]

bookings/urls.py
from django.urls import path
from . import views

app_name = "bookings"
urlpatterns = [
    path("", views.BookingList.as_view(), name="booking_list"),
    path("bookings/make-booking/<int:id>/", views.create_booking, name="make_booking"),
    path("bookings/accept/<int:id>/", views.accept_booking, name="booking_accept"),
    path("bookings/reject/<int:id>/", views.reject_booking, name="booking_reject"),
    path("bookings/cancel/<int:id>/", views.cancel_booking, name="booking_cancel"),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"
urlpatterns = [
    path("", views.home, name="home"),
    path("playgrounds/", views.PlaygroundsList.as_view(), name="playground_list"),
    path(
        "playgrounds/<int:pk>/<slug:name>/",
        views.PlaygroundDetail.as_view(),
        name="playground_detail",
    ),
    path(
        "playgrounds/create/",
        views.PlaygroundCreate.as_view(),
        name="playground_create",
    ),
    path(
        "playgrounds/update/<int:pk>/<slug:name>/",
        views.PlaygroundUpdate.as_view(),
        name="playground_update",
    ),
    path(
        "playgrounds/delete/<int:pk>/<slug:name>/",
        views.PlaygroundDelete.as_view(),
        name="playground_delete",
    ),
    path("playground-filter/", views.filter, name="playground_filter"),
]

slots/urls.py
from django.urls import path
from . import views

app_name = "slots"
urlpatterns = [
    path("", views.SlotList.as_view(), name="slot_list"),
    path("slots/create/", views.SlotCreate.as_view(), name="slot_create"),
    path("slots/update/<int:pk>/", views.SlotUpdate.as_view(), name="slot_update"),
    path("slots/delete/<int:pk>/", views.SlotDelete.as_view(), name="slot_delete"),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = "accounts"

urlpatterns = [
    path("login/", views.MyLoginView.as_view(), name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/all.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/style1.css'%}">
    <title>PlayHub</title>
</head>

<body>
    <header class="header">
        <div class="container">
            <a href="{% url 'core:home' %}" class="logo">EL3B</a>
            <nav class="nav">
                <a href="{% url 'core:home' %}"><i class="bi bi-hous-fill"></i>Home</a>
                {% if request.user.is_authenticated %}
                <a href="{% url 'core:playground_list'%}">Playgrounds</a>
                <a href="{% url 'slots:slot_list'%}">Slots</a>
                <a href="{% url 'bookings:booking_list' %}">Bookings</a>
                <a href="{% url 'accounts:logout' %}" class="btn btn-outline-success">Logout</a>
                {%else%}
                <a href="{% url 'accounts:login' %}" class="btn btn-outline-primary">Login</a>
                <a href=" {% url 'accounts:register' %}" class="btn btn-outline-success">Join Now</a>
                {% endif %}

            </nav>
        </div>
    </header>

    <main>

        <div class="container">
            {% if messages %}
            {% for message in messages%}
            <div class="alert alert-{{message.tags}}">
                {{message}}
            </div>
            {% endfor %}
            {% endif %}
            {% block content %}

            {% endblock content %}
            {% block pagination %}
            {% if is_paginated %}
            <div class="d-flex align-items-center justify-content-center mb-4">
                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                        {% if page_obj.has_previous%}
                        <li class="page-item">
                            <a class="page-link" href="{{request.path}}?page={{page_obj.pervious_page_number}}"
                                aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        {%endif%}

                        <li class="page-item"><a class="page-link" href="#">Page {{page_obj.number}} of
                                {{page_obj.paginator.num_pages}}</a></li>
                        {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="{{request.path}}?page={{page_obj.next_page_number}}"
                                aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        {% endif %}

                    </ul>
                </nav>
            </div>
            {% endif %}
            {% endblock pagination %}
        </div>
    </main>

    <footer class="footer">
        <div class="container">
            <p>&copy; Copyrigth {% now "Y" %} by <a href="#">Mostafa Nasser</a></p>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- <script src="{% static 'js/jquery-3.6.4.min.js'%}"></script> -->

</body>

</html>

templates/footer.html
<!-- <footer class="bg-dark text-white py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h5>Footer Heading 1</h5>
                <p>Some text for the first footer section.</p>
            </div>
            <div class="col-md-6">
                <h5>Footer Heading 2</h5>
                <p>Some text for the second footer section.</p>
            </div>
        </div>
        <hr>
        <p>&copy; 2023 Your Company, Inc.</p>
    </div>
</footer> -->

templates/home.html
{% extends "base.html" %}
{%load static%}

{% block content %}


<section class="feature">
    <div class="feature-content">
        <h1>EL3B</h1>
        <p>Welcome {{user.full_name|title}}</p>
        <p>The Platform where you can find playgrounds to play football</p>
        <a href="{% url 'core:playground_list'%}">Get Started</a>
    </div>
</section>
{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-sm">
    <a class="navbar-brand" href="{% url 'home'%}">EL3B</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'playground-list'%}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'slot-list'%}">Slots</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Bookings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Bookings Requests</a>
            </li>
        </ul>


        <div class="mr-auto">
            {% if user.is_authenticated %}
            <a class="btn btn-primary" href="{%url 'accounts:logout'%}">Logout</a>
            {%else%}
            <a class="btn btn-primary" href="{%url 'accounts:login'%}">Log In</a>
            <a class="btn btn-success" href="{% url 'account:register'%}">Sign Up</a>
            {% endif %}
        </div>
    </div>
</nav>